name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: localhost:5000/suika:test
          target: test
      - name: test
        run: |
          docker run --rm localhost:5000/suika:test /bin/bash -c "cmake /app && make && ctest"
